/**
 * TestimonialsSection - Verified Digital Marketing Case Studies & Client Results
 * Multi-column vertical smooth scrolling marquee with gradient mask
 */

const TESTIMONIALS = [
  {
    quote: 'Vuvuzela restructured our digital ad spend and connected our showroom WhatsApp. In month two, we generated 64 verified test drives at an acquisition cost 42% lower than our historical baseline.',
    author: 'Mike Rodriguez',
    role: 'Principal, Apex Automotive Group',
    metric: '4.2x ROAS | 64 Test Drives'
  },
  {
    quote: 'They completely re-engineered our Meta & TikTok ad creative and rebuilt our checkout funnels. Our monthly revenue surged from $45k to over $180k within 90 days.',
    author: 'Sarah Chen',
    role: 'Founder & CEO, Lumina DTC Apparel',
    metric: '+300% Revenue Lift'
  },
  {
    quote: 'With Vuvuzela DMF, our conversion rates jumped by 85% and inbound LinkedIn/Google Search ad inquiries became our #1 corporate deal generator. The ROI was undeniable within 30 days.',
    author: 'Michael Torres',
    role: 'Managing Director, Vantage B2B Advisory',
    metric: '+85% Conversion Rate'
  },
  {
    quote: 'Their technical SEO and local Google ad strategy ranked our clinics #1 in our region. We went from struggling for private implant patients to a 3-week waiting list.',
    author: 'Dr. Jennifer Walsh',
    role: 'Clinical Director, City Dental Group',
    metric: '+140% Private Patients'
  },
  {
    quote: 'What sets Vuvuzela apart is their speed-to-lead automation. Every dollar we put into paid ads is captured in seconds on WhatsApp before the lead can cross-shop.',
    author: 'David Kim',
    role: 'VP of Growth, Horizon Retail',
    metric: '4.8x Blended ROAS'
  },
  {
    quote: 'They engineered a high-intent Meta ad funnel and custom property landing page that generated two closed luxury home listings totaling €2.4M in our first quarter.',
    author: 'James Wilson',
    role: 'Principal Broker, Wilson & Co Real Estate',
    metric: '€2.4M Closed Pipeline'
  }
];

export function renderTestimonialsSection() {
  const col1 = [TESTIMONIALS[0], TESTIMONIALS[1], TESTIMONIALS[2], TESTIMONIALS[0], TESTIMONIALS[1]];
  const col2 = [TESTIMONIALS[3], TESTIMONIALS[4], TESTIMONIALS[5], TESTIMONIALS[3], TESTIMONIALS[4]];
  const col3 = [TESTIMONIALS[2], TESTIMONIALS[5], TESTIMONIALS[1], TESTIMONIALS[2], TESTIMONIALS[5]];

  const renderCard = (t) => `
    <div class="test-card">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <span style="font-size: 0.75rem; font-weight: 700; color: #10b981; background: rgba(16, 185, 129, 0.12); padding: 0.2rem 0.6rem; border-radius: 9999px; border: 1px solid rgba(16, 185, 129, 0.25);">
          ${t.metric}
        </span>
        <span style="color: #fbbf24; font-size: 0.85rem;">★★★★★</span>
      </div>
      <p class="test-body">"${t.quote}"</p>
      <div class="test-author-row">
        <div class="test-avatar-placeholder">
          ${t.author.charAt(0)}
        </div>
        <div>
          <div class="test-name">${t.author}</div>
          <div class="test-role">${t.role}</div>
        </div>
      </div>
    </div>
  `;

  return `
    <section class="testimonials-grid-section" id="case-studies">
      <span id="testimonials" style="position: absolute; top: -100px;"></span>
      <div class="container">
        <!-- Section Header -->
        <div class="section-header-center">
          <div class="pill-badge">
            <span class="pulse-dot"></span>
            <span>Client Case Studies & ROAS Proof</span>
          </div>
          <h2 class="section-title">
            The Brands We Scale to Market Dominance
          </h2>
          <p class="section-subtitle">
            Real revenue outcomes generated by Vuvuzela DMF's digital marketing, performance advertising, and conversion engineering.
          </p>
        </div>

        <!-- 3-Column Vertical Masonry Marquee -->
        <div class="testimonials-scroll-viewport">
          <div class="test-col-track">
            ${col1.map(renderCard).join('')}
          </div>
          <div class="test-col-track reverse-scroll">
            ${col2.map(renderCard).join('')}
          </div>
          <div class="test-col-track">
            ${col3.map(renderCard).join('')}
          </div>
        </div>
      </div>
    </section>
  `;
}
